version: "3.8"

services:
  react:
    depends_on:
      - nest
    build: ./requirements/react
    ports:
      - 3000:3000
    volumes:
      - ./requirements/react/app:/app
    env_file:
      - .env
    restart: on-failure

  nest:
    depends_on:
      - postgres
    build: ./requirements/nest
    ports:
      - 3001:3001
    volumes:
      - ./requirements/nest/server:/server
    restart: on-failure

  postgres:
    image: postgres:15
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./requirements/nest/server/.env
    restart: on-failure

volumes:
  db:
