version: "3.8"

services:
  react:
    depends_on:
      - nest
    build: ./react
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: on-failure

  nest:
    depends_on:
      - postgres
    build: ./nest
    ports:
      - 3001:3001
    volumes:
      - ./nest/src/image/uploads:/server/src/image/uploads
    restart: on-failure

  postgres:
    image: postgres:15
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./nest/.env
    restart: on-failure

volumes:
  db:
